Database-Plattegrond/Controllers/BeheerController.cs
using Database_Plattegrond.DatabaseService;
using Database_Plattegrond.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Database_Plattegrond.Controllers
{
    //[Authorize(Roles = "Beheerder")]
    public class BeheerController : Controller
    {
        // GET: Beheerder
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Domeinen()
        {
            ViewBag.Message = "Domeinen";

            DomeinenDatabaseService DDS = new DomeinenDatabaseService();
            DomeinenViewModel DVM = new DomeinenViewModel { Domeinen = DDS.GetHoofdDomeinen() };

            return View(DVM);
        }

        public ActionResult SoortenDatasets()
        {
            SoortDatasetDatabaseService soortDatasetDB = new SoortDatasetDatabaseService();
            SoortDatasetsViewModel soortDatasetViewModel = new SoortDatasetsViewModel { SoortDatasets = soortDatasetDB.GetAlleSoortDataset() };
            return View(soortDatasetViewModel);
        }

        public ActionResult SoortenDatasetsToevoegen(string type)
        {
            return View();
        }

        [HttpPost]
        public ActionResult SoortenDatasetsToevoegen(SoortDataset soortDataset)
        {
            SoortDatasetDatabaseService soortDatasetDB = new SoortDatasetDatabaseService();
            soortDatasetDB.InsertSoortDataset(soortDataset);
            return RedirectToAction("SoortenDatasetsBewerken", new { type = soortDataset.Type });
        }

        public ActionResult SoortenDatasetsBewerken(string type)
        {
            SoortDatasetDatabaseService soortDatasetDB = new SoortDatasetDatabaseService();
            SoortDataset soortDataset = soortDatasetDB.GetSoortDataset(type);
            return View(soortDataset);
        }

        [HttpPost]
        public ActionResult SoortenDatasetsBewerken(SoortDataset soortDataset)
        {
            SoortDatasetDatabaseService soortDatasetDB = new SoortDatasetDatabaseService();
            soortDatasetDB.UpdateSoortDataset(soortDataset);
            return View(soortDataset);
        }
    }
}

Database-Plattegrond/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Images/bloem.png" class="pull-left">
                @Html.ActionLink("Gegevens Catalogus", "Index", "Domeinen", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Domeinen", "Index", "Domeinen")</li>
                    <li>@Html.ActionLink("Datasets", "Index", "Datasets")</li>
                </ul>
                @using (Html.BeginForm("Index", "Zoeken", FormMethod.Get))
                {
                    <div class="navbar-right">
                        <ul class="nav navbar-nav">
                            @*@{ if (User.IsInRole("Beheerder"))
                                {*@
                                    <li>@Html.ActionLink("Beheerder dashboard", "Index", "Beheer")</li>
                                @*}
                            }*@
                            <li style="margin-top:8px">@Html.TextBox("zoekterm", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Zoeken" })</li>
                            <li style="margin-top:8px"><button type="submit" value="Zoeken" class="btn btn-default" aria-label="Left Align"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button></li>
                        </ul>
                    </div>
                                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer></footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>